# .readthedocs.yaml

version: 2

# Build environment configuration
build:
  os: ubuntu-20.04
  tools:
    python:
      version: "3.8"


  
# Sphinx configuration
sphinx:
  configuration: docs/source/conf.py
