# .readthedocs.yaml

version: 2

python:
  version: 3.8
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

# Sphinx configuration
sphinx:
  configuration: docs/source/conf.py
