# .readthedocs.yaml

version: 2

# Build environment configuration
build:
  os: ubuntu-20.04
  tools:
    python: "3.8"

# Sphinx configuration
sphinx:
  configuration: docs/source/conf.py

formats:
    - pdf

python:
    install:
    - requirements: docs/requirements.txt